# Generated by Django 3.1.6 on 2021-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Membership Image')),
                ('free_delivery', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('first_order_disc', models.IntegerField(default=0, verbose_name='First Order Discount')),
                ('overall_discount', models.IntegerField(default=0)),
                ('monthly_treat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Monthly Treat')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
