# Generated by Django 3.1.6 on 2021-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='recipe_book',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recipe Book Included'),
        ),
    ]
