# Generated by Django 3.1.6 on 2021-02-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_recipe_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='recipe_book',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=10),
        ),
    ]
